#!/bin/sh
#
# Run from crontab to expire old editions of online newspapers
# 

LIBRARY_LOCATION=$HOME/aviser
expirationDate=`date --date "2 days ago" "+%s"`

IFS="
"

for line in `calibredb list --with-library $LIBRARY_LOCATION -f pubdate`;do
  # Avoid processing the header line.
  lineStrippedOfTrailingSpc=`echo $line | sed 's/ *$//g'`
  if [ "id pubdate" != "$lineStrippedOfTrailingSpc" ];then
      id=`echo $line | sed 's/^\([0-9]\+\) .*/\1/g'`
      pubdate=`echo $line | sed 's/^\([0-9]\+\) \(.*\)/\2/g' | tr "T" " "`
      pubdateAsSeconds=`date --date $pubdate "+%s"`
      if [ "$pubdateAsSeconds" -lt "$expirationDate" ]; then
          # Expiring article older than the expirationDate
          calibredb remove $id --with-library $LIBRARY_LOCATION
      fi
  fi
done
