#!/bin/sh
#
# Run from crontab to fetch new editions of online newspapers
# 

RECIPEDIR=$HOME/git/calibre-recipes
EPUBFILE=/tmp/avis.epub

cd $RECIPEDIR
ebook-convert vg.recipe $EPUBFILE >/dev/null
calibredb add --with-library $HOME/aviser $EPUBFILE >/dev/null
ebook-convert aftenposten.recipe $EPUBFILE >/dev/null
calibredb add --with-library $HOME/aviser $EPUBFILE >/dev/null
rm $EPUBFILE
