#!/bin/sh
#
# Run from crontab to fetch new editions of online newspapers
# 

# Recipe dir is the dir this script resides in.
RECIPEDIR=`(cd $(dirname $0); pwd)`
EPUBFILE=/tmp/avis.epub
LIBRARY_LOCATION=$HOME/aviser

cd $RECIPEDIR
ebook-convert vg.recipe $EPUBFILE >/dev/null
calibredb add --with-library $LIBRARY_LOCATION $EPUBFILE >/dev/null
ebook-convert aftenposten.recipe $EPUBFILE >/dev/null
calibredb add --with-library $LIBRARY_LOCATION $EPUBFILE >/dev/null
rm $EPUBFILE
